### ISSUE TITLE
Once installed, utils module is not found

### ISSUE THREAD

**Issue by matclab** [frap129/layman#4]
Indeed, `utils.py` is in the `layman` module.

I suggest to modify import from `layman.py` as follow:
```python
from . import utils
from . import config
from .managers import WorkspaceLayoutManager
from .managers import MasterStackLayoutManager
from .managers import AutotilingLayoutManager
from .managers import GridLayoutManager
```

And accordingly in other python modules

**Comment by frap129** [comment]
Interesting, I didn't realize imports work differently once the module is assembled. I will work on this later today and revise the README. Thanks for reporting!

**Comment by frap129** [comment]
For now, you can just run the script directly, though I recommend you git pull first as I just pushed a pretty major bugfix

**Comment by matclab** [comment]
Yes, the import works well now. Thanks a lot.
I stil have some problems, but will open a new ticket.

**Comment by matclab** [comment]
Also, @frap129, if you could make releases (with git tags) it would be easier for me to provide an Arch Linux AUR  package with the right version. :pray:
