### ISSUE TITLE
NameError: name 'moveCmd' is not defined

### ISSUE THREAD

**Issue by nmccarty** [frap129/layman#9]
Attempting to issue a `move` command results in the following error message: https://paste.sr.ht/~thatonelutenist/4c637d423aec662158c9f2b7f96d2603c08c846d

I think it was this change/line: https://github.com/frap129/layman/commit/74b6e2d92a7ae244efcd60b167afffe2e4d2bdeb#diff-d83af3bd45770b4af4bd4e0ad62d63ca4e005036d8a82483313eeb32c24d7fe0L182 that caused the issue, it looks like the place where `moveCmd` was defined was inadvertently removed and not replaced.

**Comment by frap129** [comment]
Sorry for the delay on this! Been quite busy and haven't checked on this much. This should be fixed with the latest commit to master

**Comment by nmccarty** [comment]
No worries, thanks for the fix, I'll give it a test run later today.

**Comment by nmccarty** [comment]
Works fine now, thank you :smile:
